version: '3.5'

services:
  residence-api-db:
    container_name: residence-api-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: residenceApiSecret
      MYSQL_DATABASE: residence-api-db
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
      
