version: '3.5'

services:
  residence-api-db:
    container_name: residence-api-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: residenceApiSecret
      MYSQL_DATABASE: residence-api-db
      MYSQL_ROOT_HOST: '%'
    restart: always
    ports:
      - 3306:3306

  residence-api:
    container_name: residence-api
    image: residence-api
    depends_on:
      - residence-api-db
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      DB_HOST: residence-api-db
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: residence-api-net
      
