micronaut:
  application:
    name: residenceApi
datasources:
  default:
    url: jdbc:mysql://localhost:3306/residence-api-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'residenceApiSecret'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
