micronaut:
  application:
    name: residenceApi
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000

datasources:
  default:
    url: 'jdbc:mysql://${db-host}:3306/residence-api-db'
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'residenceApiSecret'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
